org: silto
app: make-db-lambda
service: make-db-lambda

frameworkVersion: "3"
useDotenv: true

params:
  local:
    enabled: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: us-east-1
  deploymentMethod: direct

functions:
  cronHandler:
    handler: makeDb.run
    memorySize: 512
    timeout: 300
    events:
      # Invoke Lambda function every day at 5AM UTC

      - schedule:
          # Use this cron to test locally (invokes every 5 min):
          # rate: cron(0/5 * * * ? *)
          rate: cron(0 5 * * ? *)
          enabled: ${param:enabled, false}
    environment:
      DEFIBAR_DATABASE_URL: ${env:DEFIBAR_DATABASE_URL, null}
      DEFIBAR_DATABASE_URL_SECRET: ${ssm:/aws/reference/secretsmanager/defibar-database-url, null}

plugins:
  - serverless-offline
  - serverless-offline-scheduler
